### ISSUE TITLE
example how to use

### ISSUE THREAD

**Issue by reaper7** [Lakoja/EpdDriverL#1]
Hi!,
Can you add the simplest example how to use?

tnx!

**Comment by Lakoja** [comment]
Example added - will also be available in the Arduino IDE if EpdDriverL is placed in the libraries directory.

**Comment by reaper7** [comment]
example or only note?
I don't see any example

**Comment by Lakoja** [comment]
Sorry, forgot to push...
https://github.com/Lakoja/EpdDriverL/blob/master/examples/Test_epd154/test_epd154.ino

**Comment by reaper7** [comment]
no problem, example works very well!
tnx!
